### ISSUE TITLE
DefaultRequestCulture not working when change to non-en culture in 3.1.3

### ISSUE THREAD

**Issue by lwksystem** [LazZiya/ExpressLocalization#13]
I have change the DefaultRequestCulture  to "de" but it still display in en culture when start up.

            services.AddRazorPages()
                .AddExpressLocalization<ExpressLocalizationResource, ViewLocalizationResource>(ops =>
                {
                    ops.ResourcesPath = "LocalizationResources";
                    ops.RequestLocalizationOptions = o =>
                    {
                        o.SupportedCultures = cultures;
                        o.SupportedUICultures = cultures;
                        o.DefaultRequestCulture = new RequestCulture("de");
                    };
                });

**Comment by LazZiya** [comment]
First I will give the solution, then you can read the explanation for more details.

Disable the framework [localization culture providers][5] and use only [RouteSegmentCultureProvider][1] as below:

````cs
services.AddRazorPages()
            .AddExpressLocalization<ExpressLocalizationResource, ViewLocalizationResource>(ops =>
            {
                // Use only route segment culture provider
                 ops.UseAllCultureProviders = false;
               
                // the rest of the code...
             });
````

## Explanation
When using all the [localization culture providers][5], the localization process will check all available culture providers in order to detect the request culture. If the request culture is found it will stop checking and do localization accordingly. If the request culture is not found it will check the next provider by order. Finally if no culture is detected the default culture will be used.

Checking order for request culture:
1) [RouteSegmentCultureProvider][1]
2) [QueryStringRequestCultureProvider][2]
3) [CookieRequestCultureProvider][3]
4) [AcceptedLanguageHeaderRequestCultureProvider][4]
5) Use default request culture from startup settings

So, in your case, I can guess that the localization is falling to no. 4, you can check it in your browser settings.

If you don't prefere this behavior, you can simply use only [RouteSegmentCultureProvider][1] and disable other providers as mentioned above, so when there is no culture in the route the default culture will be used.

[1]: https://github.com/LazZiya/ExpressLocalization/blob/master/LazZiya.ExpressLocalization/RouteSegmentCultureProvider.cs
[2]: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.localization.querystringrequestcultureprovider
[3]: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.localization.cookierequestcultureprovider
[4]: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.localization.acceptlanguageheaderrequestcultureprovider
[5]: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization-extensibility?view=aspnetcore-3.1#localization-culture-providers

**Comment by lwksystem** [comment]
Great, it working now. Hope you can add this to your documentation. Thanks!

**Comment by LazZiya** [comment]
Thanks for your feedback, I'll add it to the docs soon :)
