### ISSUE TITLE
Case sensitivity mismatch

### ISSUE THREAD

**Issue by morgrowe** [LazZiya/ExpressLocalization#17]
Let's say I have this:

```
@_loc.GetLocalizedString("Privacy Policy")
```

And in my `ViewLocalizationResource.cy.resx`, I have an entry for 'Privacy Policy':

![pp](https://user-images.githubusercontent.com/4726315/75338091-18040500-5886-11ea-8a82-4b70162f1c26.PNG)

When I toggle between English and Welsh, I see the string is 'translated' as expected--awesome!

However, somewhere else in my app, I may want to add this (casing exaggerated):

```
@_loc.GetLocalizedString("pRiVaCy PoLiCy")
```

Now if I toggle between English and Welsh, the string doesn't get translated--it remains as 'pRiVaCy PoLiCy' in both English and Welsh localised pages. So, I go to my `ViewLocalizationResource.cy.resx` to enter an entry for this odd casing, but the .resx file doesn't let me enter it:

![pp2](https://user-images.githubusercontent.com/4726315/75338639-f6efe400-5886-11ea-8fa6-265f0d73853f.PNG)

Please correct me if I'm wrong, but it seems the resource file is case insensitive, but the GetLocalizedString method is case sensitive, meaning I can't provide a translation for this casing?

Is there a way around this? Not sure if this is 'as designed' or a bug.

Versions:
```
    <PackageReference Include="LazZiya.ExpressLocalization" Version="3.2.0" />
    <PackageReference Include="LazZiya.TagHelpers.Localization" Version="1.3.0" />
```

Thanks
Morgan

**Comment by LazZiya** [comment]
Hi @morgrowe 

Actually it is not a bug, the default behavior of localizing strings is case-sensitive. And as you mentioned it is not possible to add "Privacy" and "privacy" to the .resx file because they are considered same from the .resx file pov.

As a workaround, you can use the entry as a key in the resx file; by adding one key for the upper-case and another for lower-case. e.g.: 

| name | value | comment |
|:---|:---|:---|
| upper_Privacy | Preifatrwydd | upper case version |
| lower_privacy | preifatrwydd | lower case version |

then you can call each one by its key:
````razor
@_loc.GetLocalizedString("upper_Privacy")

@_loc.GetLocalizedString("lower_privacy")
````
Or you can use `<localize>` html tag since you already installed `LazZiya.TagHelpers.Localization`:
````html
<h1 localize-content>upper_Privacy</h1>
<h1 localize-content>lower_privacy</h1>
````
> Notice : `LazZiya.TagHelpers.Locaization` is merged into the latest version of `LazZiya.ExpressLocalization v4.0`, currently it is in preview mode, you may see its docs in the [wiki](https://github.com/LazZiya/ExpressLocalization/wiki/Localize-TagHelper).

**Comment by morgrowe** [comment]
Ok great, makes sense. I think I'll migrate to using keys in my .resx file instead. Not sure why that didn't occur to me in the first place. 

I look forward to using v4.0 when it's out of preview mode. Thanks for all your hard work!

Cheers
Morgan
