### ISSUE TITLE
Culture is not supported

### ISSUE THREAD

**Issue by myusernamedm** [LazZiya/ExpressLocalization#33]
Hi,
Sorry for reaching out to you with another issue, I am a big fan of your expresslocalization package, but I'm having a terrible time trying to get localization working for my Identity Registration when I click submit to register a new user.

I have it setup as per the ExpressLocalizationSampleCore31 but I keep getting the below error after clicking submit, when it tries to direct the user to the RegisterConfirmation page to tell them to check their email.

**NOTE:** If I change the mailbody property in **Register.cshtml.cs** from
var mailBody = _loc.GetLocalizedString("Please confirm your account by <a href='{0}'>clicking here</a>.", HtmlEncoder.Default.Encode(callbackUrl));
to
var mailBody = "Any plain string";
then it works fine. But the email has no clickable link for the recipient.

![image](https://user-images.githubusercontent.com/39332143/121810954-9db5ea80-cc5a-11eb-957d-b9f25d93bdf2.png)
![image](https://user-images.githubusercontent.com/39332143/121811030-e8376700-cc5a-11eb-89b6-9223b4a467df.png)
![image](https://user-images.githubusercontent.com/39332143/121811056-02714500-cc5b-11eb-8738-069be917aca7.png)

**Comment by LazZiya** [comment]
Welcome @myusernamedm :)

To make sure you are calling the right method either use a named parameters:
````cs
var mailBody = _loc.GetLocalizedString(
                                     key: "Please confirm your account by <a href=“{0}”>clicking here</a>.", 
                                    args: HtmlEncoder.Default.Encode(callbackUrl));
````

Or add the culture to the params so it will go directly to the right method:
````cs
var mailBody = _loc.GetLocalizedString(
                                     CultureInfo.CurrentCulture.Name,
                                     "Please confirm your account by <a href=“{0}”>clicking here</a>.", 
                                     HtmlEncoder.Default.Encode(callbackUrl));
````

### The Reason Why?
There is two methods that accepts similar parameters with slightly small differentiation:
````cs
// Method 1
string GetLocalizedString(string key, params object[] args);
 // and Method 2
string GetLocalizedString(string culture, string key, params object[] args);
````
Both methods accepts `string` as the first param, and `params object[] args` as the last param. The second method accepts `string` also as a second param.

Due to the fact that `params object[] args` can be `null` as well, so when you call `GetLocalizedString(string, string)` it is considering that `args` are null, and instead of hitting the first method `GetLocalizedString(string, string)` it is hitting the second method `GetLocalizedString(string, string, null)`. And in this case the first param `string` is considered as the `culture` so it is throughing the exception.

I know this should have been fixed earlier, but while developing the next version I made a lot of breaking changes that led me to introduce it as a new nuget named [`XLocalizer`](https://github.com/LazZiya/XLocalizer).

**Comment by myusernamedm** [comment]
Hi,
Thank you for the detailed explanation. Is there any reason why you removed the clickable link in your two examples, or just to demonstrate the localization?

**Comment by LazZiya** [comment]
I added them, it was just for demonstration :)

**Comment by myusernamedm** [comment]
Ok thanks. The redirect is working fine now, using both options. The 'click here' link is not, but I don't think that is a localization issue. :) Thanks again!

**Comment by LazZiya** [comment]
Glad to help,

btw, try using GetLocalizedHtmlString if there are html issues.

**Comment by myusernamedm** [comment]
Thanks, unfortunately that throws a cannot convert LocalizedHtmlString to string error. If you're curious feel free to [check it out](https://stackoverflow.com/questions/67961503/net-core-email-confirmation-click-here-link-does-not-update-emailconfirmed), I honestly don't think its the localization causing my link issue, but you never know.

**Comment by LazZiya** [comment]
I checked your question, it seems that the `&` in the confirmation url is being encoded to `&amp;`.

Try replacing the `&amp;` with `&` in the `mailBody`:

````cs
mailBody = mailBody.Replace("&amp;", "&");
````

**Comment by myusernamedm** [comment]
Just an update, the 'clicking here' link does not seem to work when using the first of the two options above.
`_loc.GetLocalizedString(key: "Please confirm your account by <a href=“{0}”>clicking here</a>.",args: HtmlEncoder.Default.Encode(callbackUrl));`

But it works fine when using the 2nd option, and adding the culture.

**Comment by LazZiya** [comment]
Glad to see that you solved the issue in stackoverflow :)

Feel free to reopen if you need any more help.

Best regards,
Ziya
